apiVersion: apps/v1
kind: Deployment
metadata:
    name: weather-microservice
    labels:
    app: weather-microservice
spec:
    replicas: 1 
    selector:
        matchLabels:
        app: weather-microservice
    template: 
        metadata:
        labels:
            app: weather-microservice
        spec:
        containers:
        - name: weather-microservice
            image:  nehsa/ascii-weather:latest
            ports:
            - containerPort: 8080
            resources:
                requests:
                cpu: "100m"
                memory: "256Mi"
                limits:
                cpu: "200m"
                memory: "512Mi"
            livenessProbe:
                httpGet:
                path: /health
                port: 8080
                initialDelaySeconds: 15
                periodSeconds: 30
                failureThreshold: 3
                successThreshold: 1
                timeoutSeconds: 5
            readinessProbe:
                httpGet:
                path: /ready
                port: 8080
                initialDelaySeconds: 5
                periodSeconds: 10
                failureThreshold: 3
                successThreshold: 1
                timeoutSeconds: 2
                